"""Golden fixtures for the src/lib/orderflow parity tests, generated by the
Python REFERENCE (the blind re-tag server, outside this repo).

    python -B scripts/orderflow-fixtures/gen_reference.py <out_dir> [seq ...]

READ-ONLY against the reference:
  * imports blind_server with bytecode writing disabled (no __pycache__ lands in
    the re-tag folder) and calls build_row(seq), which only reads;
  * never touches the answers file beyond what blind_server's import reads, and
    strips `saved` / `answered` / `options` from every payload so no blind
    answer or re-tag bookkeeping ends up in a fixture;
  * selects rows by date / time / instrument only.

Per row it writes <out_dir>/row-<seq>.json.gz holding
  payload   - build_row(seq) minus the fields above
  ticks     - a digest of the exact tick frame build_row computed from
              (count, sums, first/last time, sha1 of the time + price columns)
  contracts - the (contract -> PT minutes) map build_row passed to load_ticks
"""
import sys, os, json, gzip, hashlib, io, contextlib
sys.dont_write_bytecode = True
REF = r"D:\Documents\NQ_backtest\delta_bars\entries_2026-09-30\retag_work"
sys.path.insert(0, REF)
with contextlib.redirect_stdout(io.StringIO()):
    import blind_server as bs
import numpy as np

DEFAULT_SEQS = [1, 3, 138, 382, 405, 426, 441]

captured = {}
_orig_load_ticks = bs.load_ticks


def _capturing_load_ticks(inst, minutes_by_contract, lo_pt, cutoff_pt):
    T = _orig_load_ticks(inst, minutes_by_contract, lo_pt, cutoff_pt)
    captured["T"] = T
    captured["mins"] = minutes_by_contract
    captured["lo"] = str(lo_pt)
    captured["cutoff"] = str(cutoff_pt)
    return T


bs.load_ticks = _capturing_load_ticks


def tick_digest(T):
    us = np.ascontiguousarray(T.us.values.astype("<i8"))
    px = np.ascontiguousarray(T.px.values.astype("<f8"))
    return {
        "n": int(len(T)),
        "first_us": int(us[0]) if len(us) else None,
        "last_us": int(us[-1]) if len(us) else None,
        "sum_v": int(T.v.sum()), "sum_bv": int(T.bv.sum()), "sum_av": int(T.av.sum()), "sum_nt": int(T.nt.sum()),
        "d_buy": int((T.d == 1).sum()), "d_sell": int((T.d == -1).sum()), "d_zero": int((T.d == 0).sum()),
        "sha1_us": hashlib.sha1(us.tobytes()).hexdigest(),
        "sha1_px": hashlib.sha1(px.tobytes()).hexdigest(),
    }


def main():
    out_dir = sys.argv[1]
    seqs = [int(s) for s in sys.argv[2:]] or DEFAULT_SEQS
    os.makedirs(out_dir, exist_ok=True)
    for seq in seqs:
        captured.clear()
        p = bs.build_row(seq)
        for k in ("saved", "answered", "options", "total", "batch", "batch_pos", "batch_size"):
            p.pop(k, None)
        doc = {
            "seq": seq,
            "payload": p,
            "ticks": tick_digest(captured["T"]),
            "load_ticks_args": {"lo_pt": captured["lo"], "cutoff_pt": captured["cutoff"]},
            "contracts": {c: [str(m.min()), str(m.max()), int(len(m))] for c, m in captured["mins"].items() if len(m)},
        }
        raw = json.dumps(doc, separators=(",", ":"), allow_nan=False).encode()
        fn = os.path.join(out_dir, f"row-{seq}.json.gz")
        with gzip.open(fn, "wb", compresslevel=9) as fh:
            fh.write(raw)
        r = p["row"]
        print(f"seq {seq}: {r['inst']} {r['date']} {r['time']} bars={len(p['bars']['t'])} vap={len(p['vap']['m'])} "
              f"bubbles={p['bubbles']['n'] if p['bubbles'] else 0} ticks={doc['ticks']['n']} raw={len(raw)//1024}KB gz={os.path.getsize(fn)//1024}KB")


if __name__ == "__main__":
    main()
