/**
 * /api/weekly-recap/[weekStart]
 *   GET  → returns the row (notes_md + ai_synthesis_json + timestamps)
 *   PUT  → updates notes_md only
 *
 * The AI synthesis is generated by /api/analyze-week (which also writes the
 * row); this endpoint just handles the freeform notes side.
 */

import { createClient } from '@/lib/supabase/server'
import { clientError } from '@/lib/api-error'
import { userConflict } from '@/lib/tenant-conflict'
import { NextResponse } from 'next/server'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyClient = any

export async function GET(_req: Request, { params }: { params: Promise<{ weekStart: string }> }) {
  const { weekStart } = await params
  if (!/^\d{4}-\d{2}-\d{2}$/.test(weekStart)) {
    return NextResponse.json({ error: 'weekStart must be YYYY-MM-DD' }, { status: 400 })
  }
  const supabase: AnyClient = await createClient()
  const { data, error } = await supabase
    .from('weekly_recap')
    .select('week_start_date, ai_synthesis_json, notes_md, generated_at, updated_at')
    .eq('week_start_date', weekStart)
    .maybeSingle()
  if (error) {
    if (error.code === 'PGRST205' || error.code === '42P01') {
      return NextResponse.json({
        week_start_date: weekStart,
        ai_synthesis_json: null,
        notes_md: '',
        generated_at: null,
        updated_at: null,
        migration_pending: true,
      })
    }
    return NextResponse.json({ error: clientError(error) }, { status: 500 })
  }
  return NextResponse.json(data ?? {
    week_start_date: weekStart,
    ai_synthesis_json: null,
    notes_md: '',
    generated_at: null,
    updated_at: null,
  })
}

export async function PUT(req: Request, { params }: { params: Promise<{ weekStart: string }> }) {
  const { weekStart } = await params
  if (!/^\d{4}-\d{2}-\d{2}$/.test(weekStart)) {
    return NextResponse.json({ error: 'weekStart must be YYYY-MM-DD' }, { status: 400 })
  }
  let body: { notes_md?: unknown }
  try { body = await req.json() }
  catch { return NextResponse.json({ error: 'invalid body' }, { status: 400 }) }
  if (typeof body.notes_md !== 'string') {
    return NextResponse.json({ error: 'notes_md must be a string' }, { status: 400 })
  }

  const supabase: AnyClient = await createClient()
  const { data, error } = await supabase
    .from('weekly_recap')
    .upsert(
      { week_start_date: weekStart, notes_md: body.notes_md, updated_at: new Date().toISOString() },
      { onConflict: userConflict('week_start_date') },
    )
    .select('week_start_date, notes_md, updated_at')
    .single()
  if (error) {
    if (error.code === 'PGRST205' || error.code === '42P01') {
      return NextResponse.json({ error: 'weekly_recap table missing — apply migration', migration_pending: true }, { status: 503 })
    }
    return NextResponse.json({ error: clientError(error) }, { status: 500 })
  }
  return NextResponse.json(data)
}
