/**
 * /api/monthly-recap/[month]   (month = YYYY-MM)
 *   GET  → returns the row (notes_md + ai_synthesis_json + timestamps)
 *   PUT  → updates notes_md only
 *
 * The AI synthesis is generated by /api/analyze-month (which also writes the
 * row); this endpoint just handles the freeform notes side. Mirrors
 * /api/weekly-recap/[weekStart], keyed on the month's first date.
 */

import { createClient } from '@/lib/supabase/server'
import { clientError } from '@/lib/api-error'
import { userConflict } from '@/lib/tenant-conflict'
import { NextResponse } from 'next/server'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyClient = any

const monthStartOf = (month: string) => `${month}-01`

export async function GET(_req: Request, { params }: { params: Promise<{ month: string }> }) {
  const { month } = await params
  if (!/^\d{4}-\d{2}$/.test(month)) {
    return NextResponse.json({ error: 'month must be YYYY-MM' }, { status: 400 })
  }
  const supabase: AnyClient = await createClient()
  const { data, error } = await supabase
    .from('monthly_recap')
    .select('month_start_date, ai_synthesis_json, notes_md, generated_at, updated_at')
    .eq('month_start_date', monthStartOf(month))
    .maybeSingle()
  if (error) {
    if (error.code === 'PGRST205' || error.code === '42P01') {
      return NextResponse.json({
        month_start_date: monthStartOf(month),
        ai_synthesis_json: null,
        notes_md: '',
        generated_at: null,
        updated_at: null,
        migration_pending: true,
      })
    }
    return NextResponse.json({ error: clientError(error) }, { status: 500 })
  }
  return NextResponse.json(data ?? {
    month_start_date: monthStartOf(month),
    ai_synthesis_json: null,
    notes_md: '',
    generated_at: null,
    updated_at: null,
  })
}

export async function PUT(req: Request, { params }: { params: Promise<{ month: string }> }) {
  const { month } = await params
  if (!/^\d{4}-\d{2}$/.test(month)) {
    return NextResponse.json({ error: 'month must be YYYY-MM' }, { status: 400 })
  }
  let body: { notes_md?: unknown }
  try { body = await req.json() }
  catch { return NextResponse.json({ error: 'invalid body' }, { status: 400 }) }
  if (typeof body.notes_md !== 'string') {
    return NextResponse.json({ error: 'notes_md must be a string' }, { status: 400 })
  }

  const supabase: AnyClient = await createClient()
  const { data, error } = await supabase
    .from('monthly_recap')
    .upsert(
      { month_start_date: monthStartOf(month), notes_md: body.notes_md, updated_at: new Date().toISOString() },
      { onConflict: userConflict('month_start_date') },
    )
    .select('month_start_date, notes_md, updated_at')
    .single()
  if (error) {
    if (error.code === 'PGRST205' || error.code === '42P01') {
      return NextResponse.json({ error: 'monthly_recap table missing — apply migration', migration_pending: true }, { status: 503 })
    }
    return NextResponse.json({ error: clientError(error) }, { status: 500 })
  }
  return NextResponse.json(data)
}
